/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package textfiles;

import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import static textfiles.FileData.searchWord;
import static textfiles.FileData.searchWord2;
import static textfiles.FileData.searchWordlist;
import static textfiles.PrefixTree.createTree;
import static textfiles.PrefixTree.insertWord;
import static textfiles.PrefixTree.insertWord2;
import static textfiles.GUI.tree;
import static textfiles.GUI.tree2;
import static textfiles.GUI.balance;
/**
 *
 * @author Administrator
 */

public class GUIadd extends javax.swing.JFrame {
    /**
     * Creates new form GUIadd
     */
    String vocap;
    String word;
    public GUIadd() throws IOException {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tn = new javax.swing.JTextArea();
        Edit = new javax.swing.JButton();
        savet = new javax.swing.JButton();
        add = new javax.swing.JButton();
        dec = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("เพิ่มคำศัพท์");
        getContentPane().setLayout(null);

        jLabel1.setText("คำศัพท์");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 170, 20);

        jLabel2.setText("คำแปล");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 50, 20);

        vc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcActionPerformed(evt);
            }
        });
        vc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vcKeyReleased(evt);
            }
        });
        getContentPane().add(vc);
        vc.setBounds(30, 40, 420, 30);

        tn.setColumns(20);
        tn.setRows(5);
        jScrollPane1.setViewportView(tn);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 420, 140);

        Edit.setText("แก้ไข");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit);
        Edit.setBounds(170, 260, 60, 23);

        savet.setText("เสร็จสิ้น");
        savet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savetMouseClicked(evt);
            }
        });
        getContentPane().add(savet);
        savet.setBounds(280, 260, 73, 23);

        add.setText("เพิ่ม");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(30, 260, 60, 23);

        dec.setText("ลบ");
        dec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decMouseClicked(evt);
            }
        });
        getContentPane().add(dec);
        dec.setBounds(100, 260, 60, 23);

        cancel.setText("ยกเลิก");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(370, 260, 63, 23);

        setBounds(0, 0, 482, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        vocap = vc.getText();
        word = tn.getText();
        balance.replace(vocap, word);
        vc.setText("");
        tn.setText("");
    }//GEN-LAST:event_EditActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        vc.setText("");
        tn.setText("");
        setVisible(false);
    }//GEN-LAST:event_cancelMouseClicked

    private void savetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savetMouseClicked
        // TODO add your handling code here:
        String[] vo = new String[balance.size()];
        String[] tr = new String[balance.size()];
        vo = (String[]) balance.keySet().toArray(vo);
        tr = (String[]) balance.values().toArray(tr);
        WriteFile data = new WriteFile( "C:/Users/Administrator/Desktop/builing2/vocap&tran2.txt" , false );
        try {
            data.WriteToFile("");
        } catch (IOException ex) {
            Logger.getLogger(GUIadd.class.getName()).log(Level.SEVERE, null, ex);
        }
         data = new WriteFile( "C:/Users/Administrator/Desktop/builing2/vocap&tran2.txt" , true );
        for(int i=0;i < balance.size();i++){
           if("The word was NOT found".equals(tr[i])){
           }else{
               try {
                   data.WriteToFile(vo[i]);
                   data.WriteToFile(tr[i]);
               } catch (IOException ex) {
                   Logger.getLogger(GUIadd.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
        }
        setVisible(false);
    }//GEN-LAST:event_savetMouseClicked

    private void vcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vcActionPerformed

    private void vcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcKeyReleased
        // TODO add your handling code here:
        vocap = vc.getText();
        try {
            word = searchWord2(vocap,balance);
            tn.setText(word);
        } catch (IOException ex) {
            Logger.getLogger(GUIadd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vcKeyReleased

    private void decMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decMouseClicked
        // TODO add your handling code here:
        vocap = vc.getText();
        balance.remove(vocap);
        vc.setText("");
        tn.setText("");
    }//GEN-LAST:event_decMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        vocap = vc.getText();
        word = tn.getText();
        balance.put(vocap, word);
        vc.setText("");
        tn.setText("");
    }//GEN-LAST:event_addMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new GUIadd().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(GUIadd.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JButton dec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton savet;
    private javax.swing.JTextArea tn;
    private javax.swing.JTextField vc;
    // End of variables declaration//GEN-END:variables
}
